### ISSUE TITLE
FileNotFoundError when directory URI target does not contain a trailing slash

### ISSUE THREAD

**Issue by alexiswl** [umccr/icav2-cli-plugins#148]
```yaml
inputs:
  ...
  "ora_reference":
    "class": "Directory",
    "location": icav2://umccr-workflow-testing/testdata-umccr/download-dragen-ora-v2-aws-s3-sync-download-701132e8-a402-460e-908a- 
  dc29411155bb/dragen_ora_v2
```

fails with a FileNotFoundError.

Note that

```
icav2 projectdata get  /testdata-umccr/download-dragen-ora-v2-aws-s3-sync-download-701132e8-a402-460e-908a-dc29411155bb/dragen_ora_v2
```

also fails. 

We expect this, since directories MUST have a trailing slash in ICAv2. It is, however, not intuitive. 

We should add in a feature that throws a warning and suggests adding a trailing slash if the file / directory is not found and the adjacent class attribute is 'directory'.
