### ISSUE TITLE
Consider method for generating relative mountpaths

### ISSUE THREAD

**Issue by alexiswl** [umccr/icav2-cli-plugins#212]
Necessary for v2 cttso workflow where sample fastqs need to be mounted at a particular location

**Comment by alexiswl** [comment]
Was thinking logic would look something like this

```
inputs:
  run_folder: "inputs/230312_A123456_FLOWCELLXX"
  sample_pair_ids: "my_sample_id"

mountPaths:
  - source_path: icav2://project_id/path/to/r1_fastq_file.gz
    mount_path: "{{.inputs.run_folder}}/{{.inputs.sample_pair_ids}}/{{.inputs.sample_pair_ids}}_S1_L001_R1.fastq.gz"
  - source_path: icav2://project_id/path/to/r2_fastq_file.gz
    mount_path: "{{.inputs.run_folder}}/{{.inputs.sample_pair_ids}}/{{.inputs.sample_pair_ids}}_S1_L001_R2.fastq.gz"
```
